### ISSUE TITLE
Magic Particle Spawn on Key/Trig Interaction

### ISSUE THREAD

**Issue by csammart** [JamieDeRuyter/2017_GA_Seniors#13]
Particle spawn under player?

**Comment by schung2** [comment]
nah. Player have to walk in to the particle to use magic. Since I can only make certain era use magic...

**Comment by csammart** [comment]
Mine is much more open than yours. Can you make it spawn/activate under the player when it is on the trigger range?

**Comment by schung2** [comment]
I think it should be work by level blue print. My level does not want make magic circle under character where ever player press E. If you want to make it happen like that, it should be build in level blue print.

**Comment by schung2** [comment]
gonna add additional particle under feet sphhhhhhaaaaawwww
