### ISSUE TITLE
Add checkpoint for Mayan's level

### ISSUE THREAD

**Issue by egingric** [JamieDeRuyter/2017_GA_Seniors#142]
Add a boolean that says, yes we are in mayans level. Put this in the game instance so the variable will be maintained in memory, The game instance  stays loaded during a level load. When we reload the level, check this boolean and teleport me down there if it is true.

**Comment by mbabbar87** [comment]
Fixed. Did one better.  Made a check point system where the player passes the check point anywhere in the game and after the player dies they  respawn on that last check point they passed.  :)
