### ISSUE TITLE
Fix axe collision

### ISSUE THREAD

**Issue by egingric** [JamieDeRuyter/2017_GA_Seniors#150]
It should not collide with anything other than a zombie.

**Comment by mbabbar87** [comment]
We looked into tge blueprint and it played around with the collision.  The collisions n on tge walls package file works fine however collision  in the  editor has issues and cannot be fixed as the actual VR pickup blueprint  has an issue in it self.

**Comment by egingric** [comment]
Your axe needs to work. You need to own it. 

Let me know if you need help.

**Comment by egingric** [comment]
Fixed!
