### ISSUE TITLE
Kill Trigger ChkptReset

### ISSUE THREAD

**Issue by csammart** [JamieDeRuyter/2017_GA_Seniors#34]
Checkpoint Reset

**Comment by schung2** [comment]
Check point making fail. need to fix more.

**Comment by schung2** [comment]
Check point is closer area to UI/UX design in my thought. because of it have to connect the health and magic bar. I made 2 diff check point and none of them work. for save, I tried to submit but since it has been changed by you in P4, I got problem in P4 too. Need to get help from Eric about this.

**Comment by csammart** [comment]
This isnt a UI/UX thing, it's gameplay programming. We'll check with him.

**Comment by csammart** [comment]
Players are piiiisssssed this isnt in yet. Need asap

**Comment by schung2** [comment]
gonna ask to eric and scott. goona get reservation!
