### ISSUE TITLE
make end cinematic movie play

### ISSUE THREAD

**Issue by csammart** [JamieDeRuyter/2017_GA_Seniors#9]

**Comment by csammart** [comment]
And beginning cinematic too!

**Comment by csammart** [comment]
Trigger on level open sequence, trigger on end sequence

**Comment by schung2** [comment]
video is not importing in any format. need to find way to do.

**Comment by schung2** [comment]
4.16 is not work for video. have to convert in 4.15

**Comment by schung2** [comment]
Made separate level for intro and ending now all of them connected and play well! :D
