### ISSUE TITLE
props in great hall

### ISSUE THREAD

**Issue by brouth** [JamieDeRuyter/2017_GA_Seniors#94]
dont make sense? wouldn't fit through the original box hole

**Comment by Msulliv2** [comment]
I would rather find a way to explain this away within the environment itself than limit myself to hobo props that only 1x1 sq feet in size. 
I am understanding of the issues but I do want to find a way to keep my hobo village in the great hall. It is an element I am very excited about and don't want to delete for the sake of one technicality. 
I will find a way to make this make sense.
